[build-system]
requires = ["setuptools>=68.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "discord-webhook"
version = "2.7"
description = "Explicit Discord webhook data manipulation"
readme = "README.md"
authors = [{ name = "tainn" }]
keywords = ["discord", "webhook"]
dependencies = ["httpx>=0.24.1"]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = ["black", "ruff", "mypy"]

[project.urls]
Homepage = "https://github.com/tainn/discord-webhook"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
src = ["cordhook"]
select = ["I001", "F401"]

[tool.ruff.isort]
known-first-party = ["cordhook"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = ["setuptools"]
ignore_missing_imports = true
